In [9]:
from sklearn.datasets import load_iris

iris = load_iris()
X, y_ori = iris.data, iris.target

In [12]:
from tensorflow.keras.utils import to_categorical

y = to_categorical(y_ori, 3)

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [19]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(units=8, input_dim=4, kernel_initializer="uniform", activation="relu"))
model.add(Dense(units=3, activation="softmax"))

In [20]:
model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

In [21]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 8)                 40        
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 27        
Total params: 67
Trainable params: 67
Non-trainable params: 0
_________________________________________________________________


In [22]:
model.fit(X_train, y_train, epochs=100, batch_size=10, verbose=2)

Epoch 1/100
11/11 - 1s - loss: 1.1314 - accuracy: 0.3048
Epoch 2/100
11/11 - 0s - loss: 1.0793 - accuracy: 0.3048
Epoch 3/100
11/11 - 0s - loss: 1.0593 - accuracy: 0.3333
Epoch 4/100
11/11 - 0s - loss: 1.0346 - accuracy: 0.6190
Epoch 5/100
11/11 - 0s - loss: 1.0169 - accuracy: 0.6286
Epoch 6/100
11/11 - 0s - loss: 1.0007 - accuracy: 0.6286
Epoch 7/100
11/11 - 0s - loss: 0.9832 - accuracy: 0.6381
Epoch 8/100
11/11 - 0s - loss: 0.9655 - accuracy: 0.6952
Epoch 9/100
11/11 - 0s - loss: 0.9462 - accuracy: 0.8381
Epoch 10/100
11/11 - 0s - loss: 0.9280 - accuracy: 0.9524
Epoch 11/100
11/11 - 0s - loss: 0.9098 - accuracy: 0.9333
Epoch 12/100
11/11 - 0s - loss: 0.8888 - accuracy: 0.9619
Epoch 13/100
11/11 - 0s - loss: 0.8690 - accuracy: 0.9429
Epoch 14/100
11/11 - 0s - loss: 0.8474 - accuracy: 0.9429
Epoch 15/100
11/11 - 0s - loss: 0.8268 - accuracy: 0.8857
Epoch 16/100
11/11 - 0s - loss: 0.8063 - accuracy: 0.8571
Epoch 17/100
11/11 - 0s - loss: 0.7880 - accuracy: 0.8762
Epoch 18/100
11/11 - 0s

In [25]:
hist = model.fit(X_train, y_train, epochs=100, batch_size=10, verbose=0)

In [26]:
hist.history["accuracy"]

[0.9714285731315613,
 0.9714285731315613,
 0.961904764175415,
 0.961904764175415,
 0.9714285731315613,
 0.961904764175415,
 0.9714285731315613,
 0.9714285731315613,
 0.9714285731315613,
 0.9714285731315613,
 0.961904764175415,
 0.9714285731315613,
 0.961904764175415,
 0.9714285731315613,
 0.9714285731315613,
 0.9714285731315613,
 0.9714285731315613,
 0.9714285731315613,
 0.9714285731315613,
 0.9714285731315613,
 0.961904764175415,
 0.961904764175415,
 0.9714285731315613,
 0.9714285731315613,
 0.961904764175415,
 0.9714285731315613,
 0.9714285731315613,
 0.9714285731315613,
 0.9714285731315613,
 0.9714285731315613,
 0.9714285731315613,
 0.9714285731315613,
 0.9714285731315613,
 0.961904764175415,
 0.9714285731315613,
 0.9714285731315613,
 0.9714285731315613,
 0.9714285731315613,
 0.9714285731315613,
 0.9714285731315613,
 0.9714285731315613,
 0.9714285731315613,
 0.9714285731315613,
 0.9714285731315613,
 0.9714285731315613,
 0.9714285731315613,
 0.9714285731315613,
 0.9714285731315613,
 

In [27]:
hist.history["loss"]

[0.2339402586221695,
 0.23245151340961456,
 0.2299870401620865,
 0.22728246450424194,
 0.2246217429637909,
 0.2224390059709549,
 0.22030630707740784,
 0.2177761048078537,
 0.21521534025669098,
 0.21325640380382538,
 0.21096943318843842,
 0.2087070345878601,
 0.2084423005580902,
 0.2047773152589798,
 0.20364104211330414,
 0.20091895759105682,
 0.19983620941638947,
 0.19718649983406067,
 0.19504928588867188,
 0.1931704878807068,
 0.19127041101455688,
 0.1902914196252823,
 0.1883116364479065,
 0.188328817486763,
 0.18619437515735626,
 0.18387368321418762,
 0.18100696802139282,
 0.1794063001871109,
 0.17782695591449738,
 0.17729131877422333,
 0.1752447783946991,
 0.17439764738082886,
 0.17179395258426666,
 0.17256124317646027,
 0.16837939620018005,
 0.16934621334075928,
 0.16629540920257568,
 0.1649446189403534,
 0.1629435271024704,
 0.1624288111925125,
 0.1609329730272293,
 0.15949948132038116,
 0.15813593566417694,
 0.15699036419391632,
 0.1562812775373459,
 0.15445341169834137,
 0.15482

In [28]:
from numpy.random import random
from numpy import round

X_new = round(random([3, 4]) * 10, 2)
print(X_new)

[[5.28 9.86 6.85 7.87]
 [0.21 4.08 3.63 2.59]
 [8.68 6.93 3.17 6.38]]


In [29]:
y_pred = model.predict(X_new)
print(y_pred)

[[1.5101849e-10 1.6180583e-03 9.9838197e-01]
 [2.3033972e-04 8.3660267e-02 9.1610932e-01]
 [1.8142161e-06 1.1201039e-01 8.8798785e-01]]


In [30]:
y_pred_class = model.predict_classes(X_new)
print(y_pred_class)

[2 2 2]


C:\Users\567di\anaconda3\lib\site-packages\tensorflow\python\keras\engine\sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


## MLPClassifier

In [32]:
import sklearn.datasets as d
dir(d)

mnist = d.fetch_openml('mnist_784', version=1)
X = mnist.data
y = mnist.target

C:\Users\567di\anaconda3\lib\site-packages\sklearn\datasets\_openml.py:65: RuntimeWarning: Invalid cache, redownloading file
  warn("Invalid cache, redownloading file", RuntimeWarning)


In [33]:
import numpy as np

print(X.shape)
print(y.shape)

(70000, 784)
(70000,)


In [34]:
y = y.astype(np.int)

In [35]:
np.unique(y)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
import sklearn.model_selection as ms

X_train, X_test, y_train, y_test = ms.train_test_split(X, y, test_size=0.3, random_state=1)

In [ ]:
import sklearn.neural_network as nn

pnn_clf = nn.MLPClassifier(learning_rate_init=0.001, max_iter=100, activation="relu", hidden_layer_sizes=(10, 10))
clf = pnn_clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

import sklearn.metrics as mt
print("정확도:", mt.accuracy_score(Y_test, y_pred))
print(mt.confusion_matrix(y_test, y_pred))

In [ ]:
# X_train[0]
# y_train[0]

In [ ]:
X = X / 255

In [ ]:
import tensorflow as ft
from tensorflow import keras

In [ ]:
keras.__version__

In [ ]:
help(keras)

In [5]:
import tensorflow as tf
from tensorflow import keras
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
import numpy as np
from tensorflow.keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

ModuleNotFoundError: No module named 'tensorflow'

In [ ]:
mnist = fetch_openml('mnist_784', version=1)
X = mnist.data
y_ori = mnist.target.astype(np.int)
y = to_categorical(y_ori, 10)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [ ]:
model = Sequential()
model.add(Dense(input_dim=784, units=20, activation="relu"))
model.add(Dense(units=15, activation="relu"))
model.add(Dense(units=10, activation="softmax"))

In [ ]:
model.compile(loss="categorical_crossentropy", optimizer=Adam(learning_rate=0.001), metrics=['accuracy'])

In [ ]:
model.summary()

In [ ]:
hist = model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10, batch_size=100, verbose=2)
# 원래는 epoch를 더 크게 하는게 맞음

In [ ]:
loss, acc = model.evaluate(X_test, y_test)
print("loss=", loss)
print("accuracy=", acc)

In [ ]:
y_pred_class = model.predict_classes(X_test)

In [ ]:
y_test_class = np.argmax(y_test, axis=1)

# [0, 0, 1, 0, 0, 0, 0, 0, 0, ...] =>2

In [ ]:
print(confusion_matrix(y_test_class, y_pred_class))

In [ ]:
dir(keras.optimizers)

# optimizer=RMSProp(???)
# optimizer=SGD(???)

# optimizer = "rmsprop"
# optimizer = "sgd"

In [ ]:
import matplotlib.pyplot as plt

plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.plot(hist.hitory['accuracy'], color="blue", linestyle="--", label="train")
plt.plot(hist.history['val_accuracy'], color="red", label="validation")
plt.xlabel("epoch", fontsize=15)
plt.ylabel("accuracy", fontsize=15)
plt.title("ACCURACY", fontsize=18)
plt.legend(fontsize=15)
plt.grid(linestyle="--")

plt.subplot(1, 2, 2)
plt.plot(hist.hitory['loss'], color="blue", linestyle="--", label="train")
plt.plot(hist.history['val_loss'], color="red", label="validation")
plt.xlabel("epoch", fontsize=15)
plt.ylabel("loss", fontsize=15)
plt.title("LOSS", fontsize=18)
plt.legend(fontsize=15)
plt.grid(linestyle="--")